### ISSUE TITLE
v1.1.1 Release

### ISSUE THREAD

**Issue by iuri-gg** [bigcommerce/gruf-newrelic#5]
Hi @splittingred. Would it be possible to get the latest release out for the gem sometime in next couple days?

**Comment by splittingred** [comment]
Hey @ocha ! Thanks - I was out of office the past couple of weeks. This is now done:

https://github.com/bigcommerce/gruf-newrelic/releases/tag/v1.2.0
https://rubygems.org/gems/gruf-newrelic/versions/1.2.0

Given that there were new major features (dist tracing) in this release, for semver reasons I've pushed this to 1.2.0. Thanks!
